### ISSUE TITLE
Help wanted/needed

### ISSUE THREAD

**Issue by bickycheese** [Crashdummyy/XamarinRiderDev#1]
Hi thanks for sharing this guide on how to setup Xamarin.Android on Linux!

I've followed your guide with some changes:
1. Got the latest artifacts from [Azure Devops](https://dev.azure.com/xamarin/public/_build/results?buildId=21410&view=artifacts&type=publishedArtifacts).
1. Didn't run the java setup because I already have that installed. _(see info below)_
1. Had to change this line `ln -s "/usr/lib/x86_64-linux-gnu/libzip.so.5.0" "/usr/lib/x86_64-linux-gnu/libzip.so.4"` to `ln -s "/usr/lib/libzip.so.5.1" "/usr/lib/libzip.so.4"`

I've got this setup:
> Linux Prometheus 5.7.0-3-MANJARO #1 SMP PREEMPT Wed Jun 3 03:15:33 UTC 2020 x86_64 GNU/Linux

> ➜  / java -version 
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)

> ➜  / dotnet --version
3.1.103

> ➜  / dotnet --list-sdks && dotnet --list-runtimes
2.1.807 [/usr/share/dotnet/sdk]
3.1.103 [/usr/share/dotnet/sdk]
Microsoft.NETCore.App 2.1.19 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

> ➜  / mono --version
Mono JIT compiler version 6.4.0 (makepkg/fe64a4765e6 Sat 16 May 2020 10:04:29 AM UTC)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       hybrid
        GC:            sgen (concurrent by default)

> JetBrains Rider 2020.1.3
Build #RD-201.7846.1, built on May 15, 2020
Runtime version: 11.0.7+10-b765.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
.NET Core 3.1.3
Linux 5.7.0-3-manjaro

> ➜  / ls -la /usr/lib/mono/xbuild/Xamarin/Android 
lrwxrwxrwx 1 root root 47 28 jun 20:58 /usr/lib/mono/xbuild/Xamarin/Android -> /usr/lib/xamarin.android/xbuild/Xamarin/Android

> ➜  / ls -la /usr/lib/mono/xbuild-frameworks/MonoAndroid
lrwxrwxrwx 1 root root 55 28 jun 20:59 /usr/lib/mono/xbuild-frameworks/MonoAndroid -> /usr/lib/xamarin.android/xbuild-frameworks/MonoAndroid/

![image](https://user-images.githubusercontent.com/1488543/85956795-98e42200-b988-11ea-916d-260f006464fd.png)

![image](https://user-images.githubusercontent.com/1488543/85956846-de085400-b988-11ea-8598-2b7812e3cb15.png)

![image](https://user-images.githubusercontent.com/1488543/85956856-eeb8ca00-b988-11ea-9e50-fa7bad4ffbe4.png)

![image](https://user-images.githubusercontent.com/1488543/85956876-13ad3d00-b989-11ea-98dc-b69a06f610c3.png)

Default Xamarin.Android project csproj:

```<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
        <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
        <ProductVersion>8.0.30703</ProductVersion>
        <SchemaVersion>2.0</SchemaVersion>
        <ProjectGuid>{DCE12448-7CF7-416A-B697-D47DD9191946}</ProjectGuid>
        <ProjectTypeGuids>{EFBA0AD7-5A72-4C68-AF49-83D382785DCF};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
        <OutputType>Library</OutputType>
        <AppDesignerFolder>Properties</AppDesignerFolder>
        <RootNamespace>AndroidBlankApp2</RootNamespace>
        <AssemblyName>AndroidBlankApp2</AssemblyName>
        <FileAlignment>512</FileAlignment>
        <AndroidApplication>True</AndroidApplication>
        <AndroidResgenFile>Resources\Resource.Designer.cs</AndroidResgenFile>
        <AndroidResgenClass>Resource</AndroidResgenClass>
        <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
        <AndroidUseLatestPlatformSdk>false</AndroidUseLatestPlatformSdk>
        <TargetFrameworkVersion>v9.0</TargetFrameworkVersion>
        <AndroidManifest>Properties\AndroidManifest.xml</AndroidManifest>
        <MonoAndroidResourcePrefix>Resources</MonoAndroidResourcePrefix>
        <MonoAndroidAssetsPrefix>Assets</MonoAndroidAssetsPrefix>
        <AndroidHttpClientHandlerType>Xamarin.Android.Net.AndroidClientHandler</AndroidHttpClientHandlerType>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
        <DebugSymbols>True</DebugSymbols>
        <DebugType>portable</DebugType>
        <Optimize>False</Optimize>
        <OutputPath>bin\Debug\</OutputPath>
        <DefineConstants>DEBUG;TRACE</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>4</WarningLevel>
        <AndroidUseSharedRuntime>True</AndroidUseSharedRuntime>
        <AndroidLinkMode>None</AndroidLinkMode>
        <EmbedAssembliesIntoApk>False</EmbedAssembliesIntoApk>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
        <DebugSymbols>True</DebugSymbols>
        <DebugType>pdbonly</DebugType>
        <Optimize>True</Optimize>
        <OutputPath>bin\Release\</OutputPath>
        <DefineConstants>TRACE</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>4</WarningLevel>
        <AndroidManagedSymbols>true</AndroidManagedSymbols>
        <AndroidUseSharedRuntime>False</AndroidUseSharedRuntime>
        <AndroidLinkMode>SdkOnly</AndroidLinkMode>
        <EmbedAssembliesIntoApk>True</EmbedAssembliesIntoApk>
    </PropertyGroup>
    <ItemGroup>
        <Reference Include="System" />
        <Reference Include="System.Xml" />
        <Reference Include="System.Core" />
        <Reference Include="Mono.Android" />
    </ItemGroup>
    <ItemGroup>
        <Compile Include="MainActivity.cs" />
        <Compile Include="Resources\Resource.Designer.cs" />
        <Compile Include="Properties\AssemblyInfo.cs" />
    </ItemGroup>
    <ItemGroup>
        <None Include="Resources\AboutResources.txt" />
        <None Include="Properties\AndroidManifest.xml" />
        <None Include="Assets\AboutAssets.txt" />
    </ItemGroup>
    <ItemGroup>
        <AndroidResource Include="Resources\layout\activity_main.axml">
            <SubType>Designer</SubType>
        </AndroidResource>
        <AndroidResource Include="Resources\values\colors.xml" />
        <AndroidResource Include="Resources\values\ic_launcher_background.xml" />
<!-- FIXED String.xml HERE -->
        <AndroidResource Include="Resources\values\Strings.xml" />
        <AndroidResource Include="Resources\values\styles.xml" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Xamarin.Android.Support.Design" Version="28.0.0.3" />
        <PackageReference Include="Xamarin.Android.Support.v7.AppCompat" Version="28.0.0.3" />
    </ItemGroup>
    <Import Project="/usr/lib/xamarin.android/xbuild/Xamarin/Android/Xamarin.Android.CSharp.targets" />
<!-- !!! HAD TO SET ABSOLUTE PATH FOR RIDER TO RECOGNIZE IT AS Xamarin.Android !!! -->
<!--    <Import Project="$(MSBuildExtensionsPath)\Xamarin\Android\Xamarin.Android.CSharp.targets"/>-->
</Project>
```

Now I'm getting this error and I have no idea...
>  Xamarin.Android.Support.Annotations.targets(20, 3): [MSB4062] The "Xamarin.Android.Support.BuildTasks.VerifyVersionsTask" task could not be loaded from the assembly /home/stan/.nuget/packages/xamarin.android.support.annotations/28.0.0.3/build/monoandroid90/Xamarin.Android.Support.BuildTasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
 Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

`AppCompatActivity` is not found too...

![image](https://user-images.githubusercontent.com/1488543/85957010-faf15700-b989-11ea-9734-a9396cf341bf.png)

I'm really in the blue here and hope you can help me out a bit and maybe this could help somebody with the same issues.

PS: sorry for the amount of details but the devil is in the details?

**Comment by Crashdummyy** [comment]
Well there are coming some things to my mind:
- The latter Azure builds use newer java versions. ( I am currently developing with openjdk 11.0.4 ( see update part in README ) )
- You need to use the msbuild provided by mono rather than the dotnet one
![image](https://user-images.githubusercontent.com/15139403/85980216-42a3cd00-b9e2-11ea-8f5d-dfc4489c71a3.png)

**Comment by bickycheese** [comment]
The JVM used to build on Azure is
> JetBrains JDK 8.202 r1483.37 (OpenJDK)

I'll try installing OpenJDK 11.0.4 and set it in Rider. ;)

And this is MSBuild used on Azure
> Microsoft (R) Build Engine version 16.5.0-ci for Mono
Copyright (C) Microsoft Corporation. All rights reserved.
/usr/lib/mono/msbuild/15.0/bin/MSBuild.dll /binaryLogger:bin/BuildRelease/bootstrap-build.binlog /p:Configuration=Release /t:Restore,Build Xamarin.Android.BootstrapTasks.sln
Build started 06/26/2020 23:50:40.

Regarding MSBuild, I only have these installed from Mono..?

![image](https://user-images.githubusercontent.com/1488543/85988897-037c7880-b9f0-11ea-8ab6-470e3c7ce18b.png)

**Comment by Crashdummyy** [comment]
That was some weird problem I haven't looked into further.
Apparently the current stable mono does not come with an msbuild.

On my fresh install I installed a preview version and changed apt afterwards ( [see that part](https://github.com/Crashdummyy/XamarinRiderDev#dotnet-mono-java8-and-build-tools) )

**Comment by bickycheese** [comment]
I'm running Manjaro and got the 15.x MSBuild by issuing a 
> ➜  ~ sudo pacman -Syu mono-msbuild

```:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (1) mono-msbuild-16.5.xamarinxplat.2020.02.20.11.54-1

Total Download Size:    8,72 MiB
Total Installed Size:  46,78 MiB

:: Proceed with installation? [Y/n] Y
:: Retrieving packages...
 mono-msbuild-16.5.xamarinxplat.2020.02.20.11.54-1-x86_64                       8,7 MiB  14,2 MiB/s 00:01 [###############################################################] 100%
(1/1) checking keys in keyring                                                                            [###############################################################] 100%
(1/1) checking package integrity                                                                          [###############################################################] 100%
(1/1) loading package files                                                                               [###############################################################] 100%
(1/1) checking for file conflicts                                                                         [###############################################################] 100%
(1/1) checking available disk space                                                                       [###############################################################] 100%
:: Processing package changes...
(1/1) installing mono-msbuild                                                                             [###############################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
```

Then, I've set Rider to use the 15.x MSBuild from mono and everything compiles!

But now I have a deploy error because of the newer Xamarin.Android and the java apk signer issue... :P
>   Xamarin.Android.Common.targets(2684, 3): [ADB0000] The command `"/home/stan/Android/Sdk/platform-tools/adb" -s emulator-5554 install -r "bin/Debug/AndroidBlankApp2.AndroidBlankApp2-Signed.apk"` exited with code 1:
  adb: failed to install bin/Debug/AndroidBlankApp2.AndroidBlankApp2-Signed.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl1945314489.tmp/base.apk: Attempt to get length of null array]
  Performing Streamed Install

**Comment by Crashdummyy** [comment]
Please check your logs on why signing your apk failed.
Are you already on java 11?

**Comment by Crashdummyy** [comment]
Try signing the apk yourself

```
usr/lib/jvm/jdk-11.0.4+11/bin/java -jar ~/Android/Sdk/build-tools/29.0.3/lib/apksigner.jar sign \
--ks "~/.local/share/Xamarin/Mono for Android/debug.keystore" \
--ks-pass android --ks-key-alias androiddebugkey --key-pass android \
--min-sdk-version 21 --max-sdk-version 28  /path/to/apk
```

**Comment by bickycheese** [comment]
Trying to use java 11 (openjdk) sdk...
>   Xamarin.Android.Legacy.targets(172, 5): [XA0030] Building with JDK version `11.0.7` is not supported. Please install JDK version `11.0.4`. See https://aka.ms/xamarin/jdk9-errors

Aaaargh :stuck_out_tongue:

**Comment by bickycheese** [comment]
Got it to work..

![image](https://user-images.githubusercontent.com/1488543/86120146-0ea8d480-bad4-11ea-9034-23c8adc99b40.png)

> ➜  ~ sudo pacman -Suy jdk8-openjdk

![image](https://user-images.githubusercontent.com/1488543/86120228-3730ce80-bad4-11ea-8529-745bf1ec56ac.png)

> ➜  ~ archlinux-java status                  
Available Java environments:
  java-11-openjdk (default)
  java-14-openjdk
  java-8-jdk
  java-8-openjdk

:rofl:

**Comment by bickycheese** [comment]
Note that I needed to add `Xamarin.Android.Support.Compat` _v28.0.0.3_ NuGet package too.

**Comment by Crashdummyy** [comment]
Glad you got it working :)
